const images = {
    0: require('../../assets/light-rain.jpeg'),
    1000: require('../../assets/ClearSunny.jpeg'),
    1100: require('../../assets/MostlyClear.jpg'),
    1101: require('../../assets/heavy-cloud.png'),
    1102: require('../../assets/light-cloud.png'),
    1001: require('../../assets/Cloudy.jpeg'),
    2000: require('../../assets/Fog.jpeg'),
    2100: require('../../assets/LightFog.jpeg'),
    4000: require('../../assets/Drizzle.jpeg'),
    4001: require('../../assets/Rain.jpeg'),
    4200: require('../../assets/LightRain.jpeg'),
    4201: require('../../assets/thunder.png'),
    5000: require('../../assets/snow.jpeg'),
    5001: require('../../assets/Flurries.jpeg'),
    5100: require('../../assets/LightSnow.webp'),
    5101: require('../../assets/HeavySnow.jpeg'),
    6000: require('../../assets/FreezingDrizzle.jpeg'),
    6001: require('../../assets/FreezingRain.webp'),
    6200: require('../../assets/LightFreezingRain.jpeg'),
    6201: require('../../assets/HeavyFreezingRain.jpeg'),
    7000: require('../../assets/IcePellets.jpeg'),
    7101: require('../../assets/HeavyIcePellets.jpeg'),
    7102: require('../../assets/LightFreezingRain.jpeg'),
    8000: require('../../assets/thunder.png'),
};

export default weather => images[weather];
